url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "" # the name of your site, e.g. ACME Corp.

sass:
  load_paths:
    - node_modules/

defaults:
  - scope:
      path: "assets/icons"
    values:
      image: true
